package iot

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// BatchRegisterDeviceWithApplyId invokes the iot.BatchRegisterDeviceWithApplyId API synchronously
// api document: https://help.aliyun.com/document_detail/69514.html
func (client *Client) BatchRegisterDeviceWithApplyId(request *BatchRegisterDeviceWithApplyIdRequest) (response *BatchRegisterDeviceWithApplyIdResponse, err error) {
	response = CreateBatchRegisterDeviceWithApplyIdResponse()
	err = client.DoAction(request, response)
	return
}

// BatchRegisterDeviceWithApplyIdRequest is the request struct for api BatchRegisterDeviceWithApplyId
type BatchRegisterDeviceWithApplyIdRequest struct {
	*requests.RpcRequest
	ProductKey string           `position:"Query" name:"ProductKey"`
	ApplyId    requests.Integer `position:"Query" name:"ApplyId"`
}

// BatchRegisterDeviceWithApplyIdResponse is the response struct for api BatchRegisterDeviceWithApplyId
type BatchRegisterDeviceWithApplyIdResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateBatchRegisterDeviceWithApplyIdResponse creates a response to parse from BatchRegisterDeviceWithApplyId response
func CreateBatchRegisterDeviceWithApplyIdResponse() (response *BatchRegisterDeviceWithApplyIdResponse) {
	response = &BatchRegisterDeviceWithApplyIdResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}

// CreateBatchRegisterDeviceWithApplyIdRequest creates a request to invoke BatchRegisterDeviceWithApplyId request
func CreateBatchRegisterDeviceWithApplyIdRequest() (request *BatchRegisterDeviceWithApplyIdRequest) {
	request = &BatchRegisterDeviceWithApplyIdRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Iot", "2018-01-20", "BatchRegisterDeviceWithApplyId", "iot", "openAPI")
	return
}
