package iot

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)

// BatchRegisterDevice invokes the iot.BatchRegisterDevice API synchronously
// api document: https://help.aliyun.com/document_detail/69473.html
func (client *Client) BatchRegisterDevice(request *BatchRegisterDeviceRequest) (response *BatchRegisterDeviceResponse, err error) {
	response = CreateBatchRegisterDeviceResponse()
	err = client.DoAction(request, response)
	return
}

// BatchRegisterDeviceRequest is the request struct for api BatchRegisterDevice
type BatchRegisterDeviceRequest struct {
	*requests.RpcRequest
	ProductKey string           `position:"Query" name:"ProductKey"`
	Count      requests.Integer `position:"Query" name:"Count"`
}

// BatchRegisterDeviceResponse is the response struct for api BatchRegisterDevice
type BatchRegisterDeviceResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateBatchRegisterDeviceResponse creates a response to parse from BatchRegisterDevice response
func CreateBatchRegisterDeviceResponse() (response *BatchRegisterDeviceResponse) {
	response = &BatchRegisterDeviceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}

// CreateBatchRegisterDeviceRequest creates a request to invoke BatchRegisterDevice request
func CreateBatchRegisterDeviceRequest() (request *BatchRegisterDeviceRequest) {
	request = &BatchRegisterDeviceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Iot", "2018-01-20", "BatchRegisterDevice", "iot", "openAPI")
	return
}
