package iot

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)


// QueryDeviceProp invokes the iot.QueryDeviceProp API synchronously
// api document: https://help.aliyun.com/document_detail/69633.html
func (client *Client) QueryDeviceProp(request *QueryDevicePropRequest) (response *QueryDevicePropResponse, err error) {
	response = CreateQueryDevicePropResponse()
	err = client.DoAction(request, response)
	return
}

// QueryDevicePropRequest is the request struct for api QueryDeviceProp
type QueryDevicePropRequest struct {
	*requests.RpcRequest
	IotId      string `position:"Query" name:"IotId"`
	ProductKey string `position:"Query" name:"ProductKey"`
	DeviceName string `position:"Query" name:"DeviceName"`
}

// QueryDevicePropResponse is the response struct for api QueryDeviceProp
type QueryDevicePropResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateQueryDevicePropResponse creates a response to parse from QueryDeviceProp response
func CreateQueryDevicePropResponse() (response *QueryDevicePropResponse) {
	response = &QueryDevicePropResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}

// CreateQueryDevicePropRequest creates a request to invoke QueryDeviceProp request
func CreateQueryDevicePropRequest() (request *QueryDevicePropRequest) {
	request = &QueryDevicePropRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Iot", "2018-01-20", "QueryDeviceProp", "iot", "openAPI")
	return
}
