package iot

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)


// RegisterDevice invokes the iot.RegisterDevice API synchronously
// api document: https://help.aliyun.com/document_detail/69470.html
func (client *Client) RegisterDevice(request *RegisterDeviceRequest) (response *RegisterDeviceResponse, err error) {
	response = CreateRegisterDeviceResponse()
	err = client.DoAction(request, response)
	return
}

// RegisterDeviceRequest is the request struct for api RegisterDevice
type RegisterDeviceRequest struct {
	*requests.RpcRequest
	ProductKey string `position:"Query" name:"ProductKey"`
	DeviceName string `position:"Query" name:"DeviceName"`
}

// RegisterDeviceResponse is the response struct for api RegisterDevice
type RegisterDeviceResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateRegisterDeviceResponse creates a response to parse from RegisterDevice response
func CreateRegisterDeviceResponse() (response *RegisterDeviceResponse) {
	response = &RegisterDeviceResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}

// CreateRegisterDeviceRequest creates a request to invoke RegisterDevice request
func CreateRegisterDeviceRequest() (request *RegisterDeviceRequest) {
	request = &RegisterDeviceRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Iot", "2018-01-20", "RegisterDevice", "iot", "openAPI")
	return
}
