package iot

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
	"strconv"
)

// SetDevicesProperty invokes the iot.SetDevicesProperty API synchronously
// api document: https://help.aliyun.com/document_detail/96243.html
func (client *Client) SetDevicesProperty(request *SetDevicesPropertyRequest) (response *SetDevicesPropertyResponse, err error) {
	response = CreateSetDevicesPropertyResponse()
	err = client.DoAction(request, response)
	return
}

// SetDevicesPropertyRequest is the request struct for api SetDeviceProperty
type SetDevicesPropertyRequest struct {
	*requests.RpcRequest
	IotId       string `position:"Query" name:"IotId"`
	ProductKey  string `position:"Query" name:"ProductKey"`
	Items       string `position:"Query" name:"Items"`
}

// SetDeviceNames is the request struct for set device names
func (request *SetDevicesPropertyRequest) SetDeviceNames(deviceNames []string) {
	if deviceNames == nil || len(deviceNames) == 0 {
		return
	}
	paramsMap := request.GetQueryParams()
	for i := 1; i <= len(deviceNames); i++ {
		paramsMap["DeviceName."+strconv.Itoa(i)] = deviceNames[i-1]
	}
}

// SetDevicesPropertyResponse is the response struct for api SetDeviceProperty
type SetDevicesPropertyResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateSetDevicesPropertyResponse creates a response to parse from SetDeviceProperty response
func CreateSetDevicesPropertyResponse() (response *SetDevicesPropertyResponse) {
	response = &SetDevicesPropertyResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}

// CreateSetDevicesPropertyRequest creates a request to invokeSetDeviceProperty request
func CreateSetDevicesPropertyRequest() (request *SetDevicesPropertyRequest) {
	request = &SetDevicesPropertyRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Iot", "2018-01-20", "SetDevicesProperty", "iot", "openAPI")
	return
}
