package iot

//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
//
// Code generated by Alibaba Cloud SDK Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/requests"
	"github.com/aliyun/alibaba-cloud-sdk-go/sdk/responses"
)



// SetDeviceProperty invokes the iot.SetDeviceProperty API synchronously
// api document: https://help.aliyun.com/document_detail/69579.html
func (client *Client)SetDeviceProperty(request *SetDevicePropertyRequest) (response *SetDevicePropertyResponse, err error)  {
	response = CreateSetDevicePropertyResponse()
	err = client.DoAction(request, response)
	return
}


// SetDevicePropertyRequest is the request struct for api SetDeviceProperty
type SetDevicePropertyRequest struct {
	*requests.RpcRequest
	IotId      string `position:"Query" name:"IotId"`
	ProductKey string `position:"Query" name:"ProductKey"`
	DeviceName string `position:"Query" name:"DeviceName"`
	Items      string `position:"Query" name:"Items"`
}

// SetDevicePropertyResponse is the response struct for api SetDeviceProperty
type SetDevicePropertyResponse struct {
	*responses.BaseResponse
	RequestId string `json:"RequestId" xml:"RequestId"`
}

// CreateSetDevicePropertyResponse creates a response to parse from SetDeviceProperty response
func CreateSetDevicePropertyResponse() (response *SetDevicePropertyResponse) {
	response = &SetDevicePropertyResponse{
		BaseResponse: &responses.BaseResponse{},
	}
	return
}

// CreateSetDevicePropertyRequest creates a request to invoke SetDeviceProperty request
func CreateSetDevicePropertyRequest() (request *SetDevicePropertyRequest) {
	request = &SetDevicePropertyRequest{
		RpcRequest: &requests.RpcRequest{},
	}
	request.InitWithApiInfo("Iot", "2018-01-20", "SetDeviceProperty", "iot", "openAPI")
	return
}

